# Generated by Django 5.1.3 on 2024-11-19 05:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_choice_image_question_image_quiz_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='choice',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
    ]
