# Generated by Django 5.1.3 on 2024-11-20 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_quizattempt_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
