# Generated by Django 5.1.3 on 2024-11-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_quizattempt_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=80.0, help_text='Minimum score required to pass the quiz (0-100)', max_digits=5),
        ),
    ]
