# Generated by Django 5.1.3 on 2024-11-20 22:59

import django.db.models.deletion
import quiz.models.base
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_remove_quizattempt_quiz_quizat_quiz_id_ad3002_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name', 'is_active'], name='quiz_questi_name_b6b041_idx')],
            },
            bases=(quiz.models.base.CachedMixin, models.Model),
        ),
        migrations.CreateModel(
            name='BankQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('explanation', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='bank_question_images/')),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='quiz.questionbank')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
            bases=(quiz.models.base.CachedMixin, models.Model),
        ),
        migrations.AddField(
            model_name='quiz',
            name='bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='quiz.questionbank'),
        ),
        migrations.CreateModel(
            name='BankChoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choices', to='quiz.bankquestion')),
            ],
            options={
                'indexes': [models.Index(fields=['question', 'is_correct'], name='quiz_bankch_questio_ce3bfa_idx')],
            },
            bases=(quiz.models.base.CachedMixin, models.Model),
        ),
        migrations.AddIndex(
            model_name='bankquestion',
            index=models.Index(fields=['bank', 'is_active', 'order'], name='quiz_bankqu_bank_id_ae3490_idx'),
        ),
    ]
