# Generated by Django 5.1.3 on 2024-11-21 04:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0016_fix_choice_orders'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='choice',
            options={'ordering': ['question', 'order']},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['quiz', 'order']},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'ordering': ['-created_at']},
        ),
        migrations.RemoveIndex(
            model_name='choice',
            name='quiz_choice_questio_7578ee_idx',
        ),
        migrations.RemoveIndex(
            model_name='question',
            name='quiz_questi_quiz_id_f13328_idx',
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='quiz_quiz_title_d5452b_idx',
        ),
        migrations.RemoveIndex(
            model_name='quiz',
            name='quiz_quiz_is_acti_66315a_idx',
        ),
        migrations.RemoveIndex(
            model_name='quizattempt',
            name='quiz_quizat_user_id_3d4aab_idx',
        ),
        migrations.RemoveIndex(
            model_name='quizattempt',
            name='quiz_quizat_complet_dc24c4_idx',
        ),
        migrations.RemoveIndex(
            model_name='useranswer',
            name='quiz_useran_attempt_d3207a_idx',
        ),
        migrations.RemoveIndex(
            model_name='useranswer',
            name='quiz_useran_questio_bc9392_idx',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='image',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='passing_score',
        ),
        migrations.AddField(
            model_name='useranswer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='explanation',
            field=models.TextField(blank=True, help_text='Explanation shown when this choice is selected'),
        ),
        migrations.AlterField(
            model_name='choice',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='choice',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, help_text='Image to display with the question', null=True, upload_to='question_images/'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='completed_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='score',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='time_taken',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='quizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.choice'),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='useranswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='quiz.question'),
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together={('quiz', 'user', 'started_at')},
        ),
        migrations.AlterUniqueTogether(
            name='useranswer',
            unique_together={('attempt', 'question')},
        ),
        migrations.AddConstraint(
            model_name='choice',
            constraint=models.UniqueConstraint(fields=('question', 'order'), name='unique_choice_order_per_question'),
        ),
    ]
