# Generated by Django 5.1.3 on 2024-11-21 05:55

from django.db import migrations, models


def initialize_metadata(apps, schema_editor):
    """Initialize metadata field for existing attempts."""
    QuizAttempt = apps.get_model('quiz', 'QuizAttempt')
    for attempt in QuizAttempt.objects.all():
        if attempt.metadata is None:
            attempt.metadata = {
                'total_points': 0.0,
                'earned_points': 0.0,
                'correct_answers': 0,
                'total_questions': 0,
                'difficulty_stats': {
                    'easy': {'total': 0, 'correct': 0},
                    'medium': {'total': 0, 'correct': 0},
                    'hard': {'total': 0, 'correct': 0}
                },
                'completion_time': 0.0
            }
            attempt.save()


def reverse_metadata(apps, schema_editor):
    """Reverse metadata initialization."""
    QuizAttempt = apps.get_model('quiz', 'QuizAttempt')
    QuizAttempt.objects.all().update(metadata=None)


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0017_alter_choice_options_alter_question_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizattempt',
            name='metadata',
            field=models.JSONField(
                blank=True,
                null=True,
                default=dict,
                help_text='Additional data about the quiz attempt'
            ),
        ),
        migrations.RunPython(initialize_metadata, reverse_metadata),
    ]
