# Generated by Django 5.1.3 on 2024-11-21 15:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0018_add_metadata_field"),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='question',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='choice',
            name='updated_at',
        ),
    ]
