# Generated by Django 5.1.3 on 2024-11-21 16:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0021_add_bank_and_rename_pass_mark'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='questionbank',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='question_banks', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
