# Generated by Django 5.1.3 on 2024-11-21 20:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0023_add_quiz_visibility_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='is_published',
        ),
    ]
