# Generated by Django 4.2.7 on 2024-11-22 03:11

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0025_alter_quiz_options_remove_quiz_bank_quiz_metadata_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankquestion',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='questionbank',
            name='owner',
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='metadata',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='randomize_questions',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='show_answers',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='time_limit',
        ),
        migrations.AddField(
            model_name='quiz',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='passing_score',
            field=models.DecimalField(decimal_places=2, default=60.0, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))]),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='updated_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.DeleteModel(
            name='BankChoice',
        ),
        migrations.DeleteModel(
            name='BankQuestion',
        ),
        migrations.DeleteModel(
            name='QuestionBank',
        ),
    ]
