# Generated by Django 4.2.7 on 2024-11-22 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0026_fix_quiz_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_limit',
            field=models.PositiveIntegerField(default=30, help_text='Time limit in minutes', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(180)]),
        ),
    ]
